const holdItems = [
  // Hold Battle Items
  'Ability Shield',
  'Assault Vest',
  'Big Root',
  'Binding Band',
  'Black Belt',
  'Black Glasses',
  'Black Sludge',
  'Blunder Policy',
  'Booster Energy',
  'Charcoal',
  'Choice Band',
  'Choice Scarf',
  'Choice Specs',
  'Clear Amulet',
  'Covert Cloak',
  'Damp Rock',
  'Destiny Knot',
  'Dragon Fang',
  'Eject Button',
  'Eject Pack',
  'Electric Seed',
  'Eviolite',
  'Expert Belt',
  'Flame Orb',
  'Focus Band',
  'Focus Sash',
  'Grassy Seed',
  'Grip Claw',
  'Hard Stone',
  'Heat Rock',
  'Heavy-Duty Boots',
  'Icy Rock',
  'Leftovers',
  'Life Orb',
  'Light Clay',
  'Loaded Dice',
  'Magnet',
  'Metal Coat',
  'Metronome',
  'Miracle Seed',
  'Misty Seed',
  'Muscle Band',
  'Mystic Water',
  'Never-Melt Ice',
  'Poison Barb',
  'Protective Pads',
  'Psychic Seed',
  'Punching Glove',
  'Quick Claw',
  'Razor Claw',
  'Red Card',
  'Ring Target',
  'Rocky Helmet',
  'Room Service',
  'Safety Goggles',
  'Scope Lens',
  'Sharp Beak',
  'Shed Shell',
  'Shell Bell',
  'Silk Scarf',
  'Smooth Rock',
  'Soft Sand',
  'Spell Tag',
  'Sticky Barb',
  'Terrain Extender',
  'Toxic Orb',
  'Twisted Spoon',
  'Utility Umbrella',
  'Weakness Policy',
  'Wide Lens',
  'Wise Glasses',
  'Zoom Lens',
  // Form/Evolution
  'Adamant Crystal',
  'Adamant Orb',
  'Auspicious Armor',
  'Chipped Pot',
  'Cracked Pot',
  'Draco Plate',
  'Dread Plate',
  'Earth Plate',
  'Fist Plate',
  'Flame Plate',
  'Griseous Core',
  'Griseous Orb',
  'Icycle Plate',
  'Insect Plate',
  'Iron Plate',
  'Malicious Armor',
  'Meadow Plate',
  'Mind Plate',
  'Pixie Plate',
  'Rusted Shield',
  'Rusted Sword',
  'Scroll of Darkness',
  'Scroll of Waters',
  'Sky Plate',
  'Splash Plate',
  'Spooky Plate',
  'Stone Plate',
  'Sweet Apple',
  'Tart Apple',
  'Toxic Plate',
  'Zap Plate',
  // Miscelaneous
  'Ability Capsule',
  'Ability Patch',
  'Bottle Cap',
  'Eversone',
  'Gold Bottle Cap',
  'Mirror Herb',
  'PP Max',
]

export default holdItems.map((item) => ({ name: item }))
